services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/app/data
      - ./backend/credentials:/app/credentials
    env_file:
      - ./backend/.env
    ports:
      - "8050:8050"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
